name: Build Docker Image

on:
  push:
    branches: [ main ]  # Change "main" to your branch name if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # You can choose a different runner OS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub (if pushing to Docker Hub)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/master-maths .

      - name: Push Docker image (optional)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/master-maths:latest

